"""The one place that knows every data source we pull from.

Built by importing the adapter modules rather than by hand, so it cannot drift
from reality: a source that exists is listed, and a listing that names a
missing module fails at import. A test asserts the two sets match.

Each entry carries what a human needs in order to decide whether a source is
worth keeping — where it comes from, what it costs to access, what it provides
and how it joins to everything else.
"""

import importlib
import pkgutil
from dataclasses import dataclass
from datetime import timedelta
from typing import Any

import draftkit.sources as sources_package

# Modules in the package that are infrastructure rather than data sources.
_NOT_SOURCES = {"base", "registry"}


@dataclass(frozen=True)
class SourceInfo:
    name: str
    title: str
    homepage: str
    auth: str  # none | oauth | extension
    attribution: str
    native_id: str  # the id this source speaks; how it joins
    kind: str  # identity | projection | market | platform | expert | crosswalk
    provides: tuple[str, ...]
    ttl: timedelta
    module: Any

    def as_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "title": self.title,
            "homepage": self.homepage,
            "auth": self.auth,
            "attribution": self.attribution,
            "native_id": self.native_id,
            "kind": self.kind,
            "provides": list(self.provides),
            "ttl_hours": round(self.ttl.total_seconds() / 3600, 2),
        }


def _module_names() -> list[str]:
    return sorted(
        m.name for m in pkgutil.iter_modules(sources_package.__path__) if m.name not in _NOT_SOURCES
    )


def all_sources() -> list[SourceInfo]:
    infos = []
    for module_name in _module_names():
        module = importlib.import_module(f"draftkit.sources.{module_name}")
        infos.append(
            SourceInfo(
                name=module.name,
                title=module.TITLE,
                homepage=module.HOMEPAGE,
                auth=module.AUTH,
                attribution=module.ATTRIBUTION,
                native_id=module.NATIVE_ID,
                kind=module.KIND,
                provides=tuple(module.PROVIDES),
                ttl=module.ttl,
                module=module,
            )
        )
    return infos


def by_name(name: str) -> SourceInfo:
    for info in all_sources():
        if info.name == name:
            return info
    raise KeyError(name)


def attributions() -> list[str]:
    """Credit lines, for the UI footer and the README."""
    return [info.attribution for info in all_sources()]


def as_markdown() -> str:
    """The human-readable registry, generated so docs cannot go stale."""
    lines = [
        "<!-- generated by draftkit.sources.registry; run `make docs` to refresh -->",
        "# Where draftkit gets its data",
        "",
        "Every source the app reads. This file is generated from the adapters",
        "themselves, so it cannot drift from the code.",
        "",
        "| Source | Kind | Auth | Joins on | Refresh | Provides |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for info in all_sources():
        lines.append(
            f"| [{info.title}]({info.homepage}) | {info.kind} | {info.auth} "
            f"| `{info.native_id}` | {info.as_dict()['ttl_hours']}h "
            f"| {', '.join(f'`{f}`' for f in info.provides)} |"
        )
    lines += ["", "## Credits", ""]
    lines += [f"- {a}" for a in attributions()]
    lines += [
        "",
        "## Kinds",
        "",
        "- **identity** — the canonical player universe; everything joins to it",
        "- **projection** — forecast production, which we score ourselves",
        "- **market** — where players are actually drafted, across many drafts",
        "- **platform** — one platform's own ADP *and* its own ranking list; the",
        "  difference between those two is what predicts a specific room",
        "- **expert** — published rankings and the spread of disagreement",
        "- **crosswalk** — id mapping between sources",
        "",
        "## Not used, and why",
        "",
        "- **FantasyPros** — their terms do not permit a published aggregator.",
        "  Boris Chen's tiers are expert-derived and openly published, so that is",
        "  the expert signal we use instead.",
        "- **Yahoo** — the official API needs OAuth with human-gated approval.",
        "  Worth applying for early; not reachable without it.",
        "- **Underdog** — no public API, and their terms forbid the internal one.",
    ]
    return "\n".join(lines) + "\n"
